- config/env/production.js
- config/express.js
One of the views attempts to use {{title}} which is not set.  This fixes it by setting res.locals.title from the config.app.title property so that views have access to the application title.  Also added a title property to the production env properties.
Closes #33
> Expose title property to views in order to fix blank title in HTML

- public/modules/customer/config/admin-customer.client.routes.js
- public/modules/customer/controllers/admin-customer.client.controller.js
- public/modules/customer/customer.client.module.js
- public/modules/donor/config/donor.client.routes.js
- public/modules/donor/controllers/admin-donor.client.controller.js
- public/modules/donor/donor.client.module.js
- public/modules/driver/config/driver.client.routes.js
- public/modules/driver/driver.client.module.js
- public/modules/food/config/food.client.routes.js
- public/modules/food/food.client.module.js
- public/modules/media/config/media.client.routes.js
- public/modules/media/controllers/media.client.controller.js
- public/modules/media/media.client.module.js
- public/modules/packing/config/packing.client.routes.js
- public/modules/packing/packing.client.module.js
- public/modules/questionnaire/config/questionnaire.client.routes.js
- public/modules/questionnaire/questionnaire.client.module.js
- public/modules/schedule/config/schedule.client.routes.js
- public/modules/schedule/schedule.client.module.js
- public/modules/settings/config/settings.client.routes.js
- public/modules/settings/controllers/settings.client.controller.js
- public/modules/settings/settings.client.module.js
- public/modules/users/services/authentication.client.service.js
- public/modules/volunteer/config/volunteer.client.routes.js
- public/modules/volunteer/controllers/admin-volunteer.client.controller.js
- public/modules/volunteer/volunteer.client.module.js
Move code that checks for an admin user on the client out of the controllers.  Accomplished by
- Changing the Authorization factory to a provider so it can be used in the route config areas.
- Adding a method to Authorization to check for an admin user
- Adding the resolve property to the ui-router routes that require admin access
- Setting the resolve property to the Authorization method to check for administrator
closes #34
> Fix client admin authorization code

- public/modules/customer/config/user-customer.client.routes.js
- public/modules/customer/controllers/user-customer.client.controller.js
- public/modules/donor/config/donor.client.routes.js
- public/modules/donor/controllers/user-donor.client.controller.js
- public/modules/driver/config/driver.client.routes.js
- public/modules/users/config/users.client.routes.js
- public/modules/users/services/authentication.client.service.js
- public/modules/volunteer/config/volunteer.client.routes.js
- public/modules/volunteer/controllers/user-volunteer.client.controller.js
This is applying the same logic from what I did in  [0a3832e](https://github.com/freeCodeCamp/food-bank-app/commit/0a3832e020f277336a7c5c85481c528c126a2df9) to the user routes.  
I created a `requireLoggedIn` method in the `AuthenticationProvider` that will redirect to the login page if there is not a logged in user.  Then I added this method to the ui-router resolve property of every route that requires a non-admin to be logged in. 
I think that this could be further improved to check for a role rather than simply if someone was just logged on.  This could be done by making a similar method to `AuthenticationProvider.requireAdminUser` for each type of role(i.e. requireCustomerUser, requireDonorUser).  I wanted to figure out how to just have one method requireRole(role) that you can use …
> User ui-router resolve to check for logged in user

- server/lib/address-generator.js
When this.file.length is 0 the range will still evaluate to [0] so I put a test to use [] when length is 0
> Fix bug when seeding with no addresses.csv file

- client/modules/users/components/ChangePassword.js
- client/modules/users/components/ForgotPassword.js
- client/modules/users/components/ResetPassword.js
As I worked on this, I realized that the change password page and reset password page were similar so I worked on both. There are some minor differences in handling that I left between the two because I'm not sure which you prefer. I also widened the medium columns because the error/success messages were getting squished and I thought it looked odd. Widened ForgotPassword to match and fixed lint errors.
Let me know if you think anything needs to be changed.
Closes #73
> Show server response and clear form on success

- client/modules/food/reducers/item.js
- server/controllers/food.js
- server/tests/integration/food.spec.js
and update reducer to fix bug when deleting items
I couldn't figure out how to get the reducer to update the food items properly when the api returned the category so I changed the api so that it just returns the deleted itemId.  Then the reducer can simply remove this id from the list of food items.
Closes #88
> Change the delete food item api to return the deleted food item id

- package.json
When I run `npm run dev` it does not seem to be setting NODE_ENV=development.  For example it doesn't pick up morgan in the following code
```
if (process.env.NODE_ENV === 'development') {
// Enable logger (morgan)
app.use(morgan('dev'))
```
> Fix NODE_ENV not being set when running 'npm run dev'

- client/Application.js
- client/Router.js
- client/modules/core/components/Title.js
In reference to issue #144 
As far as I am aware in order to include a ```<title>``` tag in the html page that updates, one would have to add server side rendering to the application. 
I added a quick fix. The top most component that is connected to the store ```client/Application.js``` does a check on update and changes the title if it differs from the```settings.organization``` value in the store.
> Fix title missing

- client/modules/food/components/inventory/FoodItems.js
#106 
Name changes were reseting the categoryId to ```""```.  Changed to set it to the previously set categoryId.
> Fix inventory category updating incorrectly

- server/lib/errors.js
If a user sends a bad json request such as  **POST /api/auth/signin  {"email": "password":}** the server responds with 500 'Something went wrong on the server'.  This changes it to reply 400 and informs there is a problem with the json the user submitted.
> Reply with 400 when client submits bad json

- client/modules/food/components/inventory/FoodItems.js
Partial solution to #171 
* Added form submitting on enter
* Form exit with ```esc``` seems to work
* New item, name field autofocus
* Edit item, category field autofocus
* Error warnings only show after change
Since you have the add/update button disabled until all fields are validated, I think it might be unintuitive if the user has filled in some of the fields, can see no validation errors, and yet the button is still disabled. Therefor I set the form to show validation once the user starts to interact with it.
An alternative approach could be to show no validation errors and show an active button. Then only after the user tries to submit does the form show validation errors if any occur.
As for autosuggest, is there an easy way to differentiate between autosuggest and user input?
> Update Inventory Modal

- server/controllers/media.js
- server/lib/media-helpers.js
- server/routes/media.js
Moved logic for working with media uploads to server/lib/media-helpers.js
Added deletion of files after upload
Added favicon field to multer upload in server/routes/media.js
fix for [#152](https://github.com/freeCodeCamp/pantry-for-good/issues/152)
> Uploading logo/signature should create new files and delete the old ones

- client/modules/driver/components/driver-assignment/RouteSummary.js
- client/modules/driver/components/driver-assignment/SelectedDriver.js
- client/modules/settings/components/General.js
- client/modules/settings/components/SettingsForm.js
- server/controllers/settings.js
- server/lib/seed/seed-data.js
- server/models/settings.js
Set units for distance and currency on settings model and use of the units on the route summary section of the application (only for km and mi -miles-)
All changes where tested locally with the running app.
(159) Units (km/mi, $ etc)
closes #159
> Set units for distance and corrency on settings

- server/controllers/customer.js
- server/controllers/donor.js
- server/controllers/volunteer.js
- server/lib/update-linked-fields.js
Automatic update of the address information between customers, donor and volunteers clients type when one of those is updated.
All changes where tested locally with the app running to ensure stability.
closes #153  -Saving a client should update all linked fields-
> (153) Saving a client should update all linked fields

- client/components/questionnaire/widgets/food-preferences/FoodItem.js
- client/modules/customer/reducer.js
- client/modules/food/reducers/category.js
- client/modules/food/reducers/item.js
- server/controllers/food.js
- server/models/food.js
- server/tests/integration/food.spec.js
When deleting food categories and items just set a deleted flag instead of deleting from the database in order that other documents that reference them can still access them.
Closes #220
> Use delete flag on food model to indicate deletion

- client/modules/customer/components/CustomerEdit.js
- server/config/env/all.js
- server/config/express.js
* Automatically expire session if idle for an hour. see `server/config/env/all.js:14`.
* Also fixed a bug that allowed user to set themselves as active even if they're rejected. (I was the one who introduced the bug with my last PR.)
Closes #22
> Add automatic session expiration (#22)

- server/controllers/food.js
- server/tests/integration/food.spec.js
The query in createItem() is supposed to check for an item with the same name where deleted is false.  Instead it was searching for a food item with the same name and a separate food item where deleted is false.
> Fix query that checks if food item exists already and is not deleted

- common/constants.js
- server/controllers/customer.js
- server/routes/customer.js
Customer controller will restrict status changes for non-admins when updating a customer status from Reject or Pending.
Attempting to resolve Issue #227 .
> customer controller middleware restricting customer status updates

- common/placeholders.js
- server/lib/mail/mail-helpers.js
- server/lib/seed/seed-data.js
To fix #119 second point:
A new placeholder for the receipt in common/placeholders. It should be required and added to the email during db seeding, like the password reset url placeholder. It should render a table with the donated items and values and total.
A new place holder was created with a table structure to send the donation detail in the receipt.
All changes where tested locally and with the lint command!
> (#119-2)New PlaceHolder in common/placeholders

- server/tests/integration/questionnaire.spec.js
Adds questionnaire server tests.
Note: There is a create method on the controller but it isn't reachable from a route (commented out in routes file).
> Questionnaire server tests

- server/controllers/donation.js
server/controllers/donation.js - when creating new donation model,
‘value’ inside request body is sent as string from client. So we can convert ‘item.value’ to Number inside reduce function which is being used for assigning new value for ‘total’ key
closes #243
> converts donation.total from string to number

- package.json
Force use of `admin-lte` ~2.3, as 2.4.0 is currently breaking the webpack compile.
Addresses #255.
> Fix `admin-lte` version issue

- common/placeholders.js
- server/lib/mail/mail-generator.js
- server/lib/seed/seed-data.js
- server/models/settings.js
#119 -3 To make it look a bit more receipt like, there could be another table as part of the donation receipt with the organization details and EIN number from general settings.
Solution tested locally and checked with lint command.
> (#119-3)To make it look a bit more receipt like, table with EIN

- client/modules/core/css/core.css
- client/modules/customer/components/CustomerList.js
- client/modules/donor/components/DonorList.js
- client/modules/driver/components/DriverList.js
- client/modules/food/components/Schedule.js
- client/modules/food/components/inventory/FoodItems.js
- client/modules/food/components/packing/Packages.js
- client/modules/food/components/packing/PackingList.js
- client/modules/users/components/UserList.js
- client/modules/volunteer/components/VolunteerList.js
Instead of showing the dropdown menu orientated to the bottom of the button, invert it and show it above, to prevent the dropdown menu to overflow out of the bottom of the page. This happened to me quite often, when the page wasn't scrolled down completely and the pagination button was just barely visible. When clicking it I was only able to see like the "10" and "20" but often the "30" and "50" were not visible at all.
Not entirely sure this is in the right place, but I couldn't really find any specific styles for this except the default bootstrap styles. Feel free to guide me to the right place.
> Invert orientation of the pagination dropdown menu

- client/modules/driver/components/driver-assignment/map/Markers.js
- client/modules/driver/reducers/assignment.js
- client/modules/driver/reducers/assignment.spec.js
- client/modules/driver/reducers/assignment.js
Apparently, MarkerClusterer’s bound is ‘larger’ than it is supposed to. As a result,  `MarkerCluster.isMarkerInClusterBounds()` returns true to those markers located nearby but not inside the cluster.
So, how about we instead use `MarkerClusterer.getMarkers()`, which returns array of the markers assigned to this cluster. Then we can compare their location coordinates (lat,lng) with those of customer markers, and return those match each other. 
My concern is the way the code compares customer makers to markers in each cluster. It looks for matching lat/lng coordinates by ‘assuming’ all customer makers have coordinates with 6 decimal points. (this works just fine with current data set)
- client/modules/driver/reducers/assignment.spec.js 
Above …
> strict selection of markers when click MarkerCluster

- client/modules/questionnaire/reducers/api.spec.js
The state in this test did not have normalized data in it.  For some reason normalizr versions before 3.2.4 didn't have a problem with it so the tests have been passing up until recently when 3.2.4 was released.
> properly normalize state data in api.spec.js getLinkableFields test

- client/modules/food/components/inventory/Category.js
added moveCursor function to be called onFocus for Category edit fields.
This should complete the Category section from [Food Inventory #171](https://github.com/freeCodeCamp/pantry-for-good/issues/171)
> Autofocus on edit cursor position

- client/modules/settings/components/General.js
Fix for issue #281, now address (under settings/general) has an '*' to show that it is a required field.
> fixes #281 shows address as required in general settings

- client/modules/food/components/inventory/FoodItems.js
Addresses item in [Food Inventory #171 ](https://github.com/freeCodeCamp/pantry-for-good/issues/171)
Selecting an existing food item from autosuggest now moves focus to quantity.  If editing an existing item, moves cursor to end of line like when editing categories.  
**Added:** 
- inputRef to foodQuantity FormControl
- handChange.foodName now uses callback this.validateFocus
- validateFocus function calls validate like before, focus on quantity.focus, moves cursor
> Selecting item from autosuggest now moves focus to quantity

- client/modules/driver/driver.css
Fixes the driver routes list table that had the addresses going out of the table.
closes #291
> Fixes broken driver routes list CSS

- server/config/env/secrets-template.js
- server/lib/geolocate.js
In /server/lib/geolocate.js we use the node-geocoder to geocode addresses — [line 6, here](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/server/lib/geolocate.js#L6). 
However, we do not initialize the geocoder with an API key — [NPM usage example](https://www.npmjs.com/package/node-geocoder)
```javascript
var options = {
provider: 'google',
apiKey: 'YOUR_API_KEY', // we do not have this line (!!)
formatter: null
};
```
After a few requests for address validation (edit an address and click "Update"), Google API throws an OVER_QUERY_LIMIT error:
```
Error: Status is OVER_QUERY_LIMIT. You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_
at …
```
> add API key to secrets template and node-geocoder

- client/modules/driver/components/driver-assignment/RouteSummary.js
- client/modules/driver/components/driver-assignment/SelectedDriver.js
Suggest route was not working. This was because the preferred unit of distance was not being passed to the `<RouteSummary>` component via the `settings` prop.
`PropTypes` were defined on `<RouteSummary>` to prevent further problems.
As a side note, this problem was made more difficult to find because the error was being swallowed by [this line](https://github.com/freeCodeCamp/pantry-for-good/blob/9d54d5ebc95d0ba2f7e14251745024920cb93709/client/modules/driver/reducers/route.js#L100). Might want to consider re-throwing unexpected errors in these situations.
Closes #297
> Add missing settings prop to <RouteSummary>

- client/modules/driver/reducers/assignment.js
There are two ways that a driver ID can be sent to the code to set the filter. One is by selecting a value from a SELECT dropdown box on the Route Assignment page. Another is to click one of the "Driver Cards" at the top of the page.
The dropdown box sends ev.target.value to dispatch(setFilter()) when it is selected. `ev.target.value ` is of type string, even though its value was set as the Numeric driver._id in the element:
[L22 FilterCustomers.js](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/client/modules/driver/components/driver-assignment/FilterCustomers.js#L22)
`<option key={driver._id} value={driver._id}>`
However, the Driver Cards at the top of the component sets the filter by passing ID directly rather than through an event:
[L12: …
> Enforce type equality in customer list filter function

- common/schemas.js
Normalizr doesn't like recursive schemas, and while `denormalize()` will fix this for you, `normalize()` will not.
Problem arose when attempting to update a volunteer with customers. The volunteer object would be normalized in `formatRequestBody()` of _client/store/middleware/api.js_, but volunteer holds references to customers and the customers hold a reference back to the volunteer, which results in a `RangeError` being thrown due to infinite recursion.
Closes #301
> Make volunteer schema non-recursive

- client/Router.js
- server/controllers/food.js
- server/routes/food.js
The INVENTORY and SCHEDULE roles were not being properly enforced, allowing any volunteer to perform related tasks.
* Restrict access to /inventory and /schedule based on role.
* Add more granular permissions to the food controller.
* Explicitly require authenticated user for all food endpoints.
I am not all that familiar yet with the code base, so the permissions I set up are likely not correct. But I did try to follow @jspaine's initial suggestions.
Closes #303
> Improve food related authorization

- client/modules/driver/reducers/helpers.js
- client/modules/driver/reducers/route.js
`requestGoogleRoute()` currently swallows all errors. Better define expected errors rejected from `getGoogleRoute()` so all others can be rethrown.
Also removed an unnecessary try catch block from `getGoogleRoute()`.
> Log unexpected errors from `requestGoogleRoute()`

- client/modules/page/components/PageEditor.js
When switching between Page and E-mail editors, we grab the current pages and stash them in state in `PageEditor`. This component's return method passes `page.body` to the ReactQuill component as the value to display in the textarea. However, if `page.body` is undefined, the ReactQuill component doesn't mount properly, giving an error like this:
When you then try to switch between the editor types, the body contents do not display properly, since the ReactQuill component holding the body text did not mount properly. The component receives all the updates (if you console.log out the page.body, the expected body shows up), but since ReactQuill failed to render once, it's "broken" and will not respond to any additional state changes. 
The issue is that PageEditor, a child of EditPages, can …
> null check page.body before passing to react-quill

- .babelrc
- .gitignore
- .nycrc
- client/.babelrc
- package.json
With these changes `npm run coverage` will generate a test coverage report in `coverage/lcov-report/index.html`
The one thing I don't like is that I think the babel-plugin-istanbul plugin also gets used with `npm test` when you want to run just the tests without creating a coverage report.  From what I understand, istanbul adds extra code to every statement to keep track of what statements run.  I don't like the idea of all that unnecessary code being put into regular test runs.  
If you have any ideas on how to resolve this or if this shouldn't be a concern please let me know.
> Add istanbul test coverage

- server/controllers/donation.js
Checks that donation value is NaN on the server, and throws a BadRequestError if so.
> fixes #243 - validates that donation is NaN on server

- client/Application.js
- client/components/router/guestOrRedirect.js
- client/index.html
- client/modules/users/UserRouter.js
- client/modules/users/components/ForgotPassword.js
- client/modules/users/components/SignIn.js
- client/modules/users/components/SignIn.spec.js
- client/modules/users/components/SignUp.js
- client/store/middleware/api.js
- client/store/middleware/api.spec.js
- server/routes/donation.js
- server/routes/packing.js
- server/routes/questionnaire.js
- server/routes/settings.js
If the user continues using the app after having timed out, all requests will fail, some silently. This PR instead clears the client session when the server signals a session timeout.
The main change was simple. In the api middleware, if a response has status 401, clear the user from client state. b1cbc57
To support this change the server needed to return 401 responses consistently when the user was not authenticated. 7262004
On logging out an admin, the formatting was off; there was an empty space where the sidebar used to be. This is because of DOM manipulation being done in `<Application />` using _jQuery_ instead of _React_. c0c9105.
The last change wasn't strictly necessary, it was a simple refactor I did while reviewing how the client handled authorization. I thought it might be …
> Logout on expired sessions

- client/modules/core/css/core.css
Removes float: right and instead uses absolute positioning, which seems to fix the Firefox-specific UI problem.
> fixes #323 - aligns selectors in navbar in Firefox

- client/modules/food/components/packing/Packages.js
On the Packing List page the column heading 'status' was changed to 'Status' so it is capitalized like the other table headings.
This was suggested by @kenjiO
> Capitalized the column heading status on the Packing List page

- server/controllers/settings.js
- server/routes/settings.js
Recent changes (by me) to authorization mistakenly required a logged in user in
order to access the settings. These are required to render the content
pages, so everyone should have access to them.
> Allow guests to get settings

- client/components/form/Checkbox.js
The prop was marked as required but was often not provided.
> Do not require name for <Checkbox>

- server/controllers/users/profile.js
- server/routes/users.js
"Fist Name" => "First Name"
While I was there I made use of the `usersController.requiresLogin()` middleware to enforce a signed in user, just to keep things consistent.
Also, `user = extend(user, req.body)` is a little misleading. `lodash.extend()` already mutates the object so there is no need to assign to `user` again. Only meaningful if you were expecting `req.user` to remain untouched, but I thought I'd bring it up.
> Fix spelling error in profile controller

- server/controllers/customer.js
- server/tests/integration/customer.spec.js
> Prevent deleting customers with packages

- client/modules/users/components/SignUp.js
A couple refactorings accompany this.
Changes `render = () => {` to `render() {`. The first binds the render function each time a component instance is created, but this is unnecessary as render is already called with component instance. It just creates needless functions.
The state and props are destructured to avoid continuously reaching into the respective objects and to make the methods, i.e. `this.onFieldChange`, more obvious.
> Show password confirmation warning only when fields touched

- server/controllers/users/profile.js
Although the endpoint is used to update any user, it always used the logged in user (`req.user`) as the base.
> Use appropriate user in profile.update()

- README.md
Updated Installing API Keys section, because there is a script executed after installation that copies the secrets.js and it is not necessary to copy the file manually
> Updated installing API Keys section on README

- client/modules/users/components/EditUser.js
- server/controllers/users/profile.js
This adds the ability to promote/demote users to/from admin status. Admins can't demote themselves. Although they're not prevented from trying, only told after the fact that they can't with an error message.
Could use some input on design/where exactly you want this feature. I'm real bad at design.
> Add admin toggle to edit user page

- server/controllers/customer.js
- server/controllers/donation.js
- server/controllers/donor.js
- server/controllers/users/authentication.js
- server/controllers/users/profile.js
- server/controllers/volunteer.js
Instead of dumping whatever the user gives you into a model, selectively take or reject specific keys.
I was a little uncertain about the client controllers. I wrote something for the create method, but I imagine that `email`, `firstName`, and `lastName` could be omitted as well, instead pulling those values off of the related user. Unless there is a reason to allow those values to diverge.
I didn't touch the update method. It's probably fine as the authorizations are restricted to admins and the clients themselves, but it's worth some thought.
Addresses #337, not sure if it resolves it though.
> Filter params in controller

- server/controllers/users/profile.js
- server/tests/unit/profile.spec.js
The recently added param filtering removed `isAdmin` from user, which prevents the admin toggle from working.
Also fixed the cannot demote self check. Was using `userId` from params, but against convention, the id is not included in the path but the request body.
The admin toggle code was refactored for clarity and a test was added.
Now that I look at it, I had to change the authenticated user is admin check as well. Not sure how this was working before...
> Fix profile controller update method

- client/modules/driver/components/DriverRoute.js
- client/modules/driver/components/driver-assignment/SelectedDriver.js
- client/modules/driver/reducers/route.js
- client/modules/driver/reducers/route.spec.js
These are time-consuming and expensive requests, so I limited them to one outgoing.
I hard-coded the selector in [the route "reducer"](https://github.com/freeCodeCamp/pantry-for-good/compare/staging...wacii:feature/limit-route-requests?expand=1#diff-c891cd2901f7fe7ee3be201fef407506R88). The route selector factory is defined in the same file, so I can't reference the ultimate selectors without pulling apart the reducer file.
> Limit route requests

- common/constants.js
- server/config/mailer.js
- server/controllers/users/password.js
- server/lib/mail/mail-helpers.js
- server/lib/seed/seed-data.js
Closes the Issue #157 add a 'you signed up with your google account' email.
All changes were locally tested and lint checked.
> (#157) add a 'you signed up with your google account' email 

- client/modules/customer/reducer.js
- client/modules/customer/reducer.spec.js
- server/routes/customer.js
- server/tests/helpers.js
- server/tests/integration/customer.spec.js
Separated the tests into endpoints to better see what was and wasn't being tested.
Removed a duplicate read customer route and moved the list customer route under admin. That is how it was being used anyways.
> Revise customer integration tests

- client/modules/food/components/inventory/FoodAddEditForm.js
- client/modules/food/components/inventory/FoodAddEditForm.spec.js
- client/modules/food/components/inventory/FoodItems.js
- client/modules/food/components/inventory/FoodItems.spec.js
I think the FoodItem.js component is doing too much and the code is hard to reason with.  So I kept the functionality for listing the food items in that file and moved all the functionality dealing with the form for adding and editing foods into a new FoodAddEditForm component.
> Refactor FoodItems into two components

- client/modules/food/components/packing/PackingList.js
closes #356 
The module for the table `react-bootstrap-table` doesn't have a nice way of attaching listeners to cells. I wrapped the contents of each cell with an `OverlayTrigger`. Not sure if this adds too much extra markup.
> Feature - Add Tooltip to Packed Package List Preferred Foods

- client/modules/users/UserRouter.js
Added a fix similar to the one implemented for issue #370 to ensure that the signup form is not cleared when an invalid email address is entered, and the incorrect email error is properly shown.
closes #372
> fix: signup form validation issue

- client/modules/core/components/sidebar/Sidebar.js
withRouter is not needed on the Sidebar component because it doesn't use any props from provided by it
> remove unused withRouter from Sidebar

- client/modules/core/components/Header.js
I removed the route and path props from the Header component because the Navbar wasn't using the path property being passed to it.  And the route prop was only used for getting the path.
> removed unused path and route props in Header
