- public/modules/core/controllers/sidebar.client.controller.js
- public/modules/driver/config/driver.client.config.js
- public/modules/driver/controllers/user-driver.client.controller.js
1. user-driver.client.controller.js ---> A variable had been initialised as an object which was causing an error when it was being filtered. 
2. driver.client.config.js ---> The state change required the 'user._id' as a parameter which was causing the server to send a '404' back as the route was unavailable.
3. sidebar.client.controller.js ----> There are no changes here, I guess it's from the whitespaces after I deleted 'console.logs'.
Let me know if you find anymore, I'll continue with this issue https://github.com/freeCodeCamp/food-bank-app/issues/10 in the mean time.
> bug fixes when signed in as a volunteer

- public/modules/food/controllers/food.client.controller.js
- public/modules/food/views/foods.client.view.html
Hello. I added report generation to inventory menu.
foods.client.view.html --> add dt-options='foodCtrl.dtOptions'
food.client.controller.js --> add dtOptions object which is determine datatable options
I hope this is enough for the issue. If not then i will work on it further.
closes#7
> add report generation to inventory menu

- app.json
- package.json
- server/routes/media.js
add npm scripts to build server and client separately
fix app name and repo in app.json
> fix media path in production

- client/modules/customer/components/CustomerList.js
- client/modules/donor/components/DonorList.js
- client/modules/driver/components/DriverList.js
- client/modules/food/components/inventory/Category.js
- client/modules/food/components/inventory/FoodItems.js
- client/modules/food/components/inventory/NewCategory.js
- client/modules/volunteer/components/VolunteerList.js
I don't know if we should label table column buttons or not. In some tables there's plenty of space and others are pretty cramped. Icons are usually pretty obvious but the route icon in the drivers table isn't really.
> table fixes

- client/Router.js
- client/components/questionnaire/Questionnaire.js
- client/components/withConfirmNavigation.js
- client/modules/core/components/Dialog.js
- client/modules/core/css/core.css
- client/modules/core/reducers/dialog.js
- client/modules/core/reducers/index.js
- client/modules/core/reducers/menu.js
- client/modules/page/components/EditPages.js
- client/modules/page/components/PageEditor.js
- client/modules/questionnaire/Questionnaire.js
- client/modules/questionnaire/reducers/editor/index.js
- client/modules/settings/components/SettingsForm.js
- client/store/selectors.js
> add confirm navigation dialog

- package.json
- webpack.config.dev.js
- webpack.config.prod.js
~~fixes 96?~~ it was working for me in chrome but not firefox, with this it works in firefox too.
edit - dates are still buggy, but editing frequency seems to work
> add autoprefixer, babel polyfill

- client/components/questionnaire/widgets/food-preferences/FoodCategory.js
- client/modules/driver/components/driver-assignment/DriverList.js
- client/modules/driver/components/driver-assignment/FilterCustomers.js
- client/modules/questionnaire/components/FieldEdit.js
use optgroup for grouping select options
> fix button cant be flex container in ff

- client/app.js
- client/components/questionnaire/Questionnaire.js
- client/components/withConfirmNavigation.js
- client/modules/core/reducers/dialog.js
- client/modules/customer/components/CustomerEdit.js
- client/modules/customer/components/CustomerView.js
- client/modules/donor/components/DonorEdit.js
- client/modules/donor/components/DonorList.js
- client/modules/page/components/EditPages.js
- client/modules/questionnaire/Questionnaire.js
- client/modules/volunteer/components/VolunteerEdit.js
- client/modules/volunteer/components/VolunteerView.js
I didn't add to food item delete, not sure it's needed there?
closes #107, closes #98
> more confirmations

- client/modules/users/components/SignUp.js
- server/config/strategies/google.js
- server/routes/users.js
> When using google to signup, allow the user to select the account type

- client/modules/customer/components/CustomerCreate.js
- client/modules/customer/components/CustomerView.js
- client/modules/donor/components/DonorCreate.js
- client/modules/volunteer/components/VolunteerCreate.js
- client/modules/volunteer/components/VolunteerEdit.js
> add missed redirects, redirect on delete

- server/config/express.js
- server/lib/enforce-ssl-middleware.js
think we can delete some of that stackerror, views/locals cache
> clean up express config

- client/modules/food/components/packing/Packages.js
- client/modules/food/components/packing/PackingList.js
- client/modules/food/reducers/index.js
- client/modules/food/reducers/packing.js
- server/controllers/packing.js
- server/routes/packing.js
- server/tests/integration/packing.spec.js
Also made minor improvements to packing controller pack function and added more tests
> Add ability to unpack a package that has been marked packed

- client/components/error/Error.js
- client/modules/customer/reducer.js
- client/modules/users/UserRouter.js
- client/modules/users/components/SignUp.js
- client/store/middleware/api.js
- server/config/express.js
- server/controllers/food.js
- server/controllers/packing.js
- server/controllers/users/authentication.js
- server/controllers/users/password.js
- server/lib/errors.js
- server/models/customer.js
- server/tests/integration/user.spec.js
Added an error class for validation errors for redux form submit validation, and changed the other validation error formats to match. Removed some extra try catches and fixed #167
> Validation errors

- client/modules/food/components/packing/PackingList.js
a fix to disable mark packed button when no checkboxes are selected, this closes #166
> Mark Packed button is disabled

- client/modules/volunteer/reducer.js
- server/controllers/delivery.js
> fix drivers not showing in delivery pages

- client/.babelrc
- client/modules/food/reducers/packing.js
- client/modules/food/reducers/packing.spec.js
- server/controllers/packing.js
I'll put this separate because you're working on it. You can simplify the response handling in the action creators by formatting the response so normalize can work directly on it.
> simplify packing action creators, test

- client/modules/food/components/Schedule.js
- package.json
Editing start date and frequency was not possible in firefox (and other non-chrome browsers?). This PR aims to fix both. Since this is also my first PR, and I would like to do more, I would like your feedback and a project overview. (I looked at the developer's guide and its outdated. Even a general idea of how everything is organized and a list of supporting libraries would be great.) 
closes #96
> Fix editing Food Schedule Frequency and Start Date

- client/modules/food/components/packing/PackModal.js
- client/modules/food/components/packing/Packages.js
- client/modules/food/components/packing/PackingList.js
- client/modules/food/reducers/packing.js
- server/controllers/packing.js
- server/models/package.js
- server/tests/integration/packing.spec.js
> Add a packing modal to select items for a package

- server/controllers/packing.js
- server/tests/integration/packing.spec.js
and do all validation before saving
fixes #192.  Any invalid data will cause the whole operation to fail without saving anything.
> Update server packing controller pack method to use the mongoose model validator

- client/modules/food/components/packing/PackModal.js
- client/modules/food/components/packing/PackingList.js
I thought this will make the app more flexible in case when making a package they sometimes want to do an exception and add something not scheduled for the current week.
> Allow the user to select items not scheduled for this week when packing

- package.json
Aborts commit if lint or tests fail
> add pre-commit hook to lint and test

- client/modules/core/components/Footer.js
Changed the copyright year on client/modules/core/components/Footer.js fixes
> Fixed copyright year

- client/modules/customer/components/CustomerEdit.js
Please let me know if you want me to make any changes to the text.
closes #125
> Allow customers to set status (#125)

- client/modules/food/components/inventory/FoodItems.js
> Adding confirm dialog to item deletion in inventory page

- server/controllers/customer.js
- server/controllers/donor.js
- server/controllers/volunteer.js
- server/lib/update-linked-fields.js
About #153 issue, all the functions were combined in only one that it is exported and use "clientRole" to work internally.
The changes were tested locally on a running app.
This change was done following a recommendation.
> (#153) final united functions recomendation

- client/modules/customer/components/CustomerCreate.js
- client/modules/donor/components/DonorCreate.js
- client/modules/volunteer/components/VolunteerCreate.js
so the saveXX action creators will create the client instead of trying to update
> omit id when copying initial client data from user

- client/modules/food/components/packing/PackModal.js
> modal window button (#200)

- client/modules/users/UserRouter.js
- client/modules/users/components/ConfirmNewGoogleAccount.js
- server/config/strategies/google.js
- server/routes/users.js
> If user with no account attempts to sign in with google ask to create an account

- client/modules/users/components/UserList.js
Typo on the Accounts page title
> accounts typo

- client/modules/settings/components/General.js
- server/models/settings.js
EIN field in the general settings was created to contributed to the solution of the issue #119.
The changes were tested locally and was also run the eslint check for client an server without any error.
> EIN field in the general settings

- server/controllers/donation.js
Related to issue #119 - found a bug that prevents non-admin donors from creating their own donations.
> donation controller bug not allowing donors to create donations

- client/modules/donor/components/DonorList.js
> Closes Donor Delete modal after deleting donor

- client/modules/users/components/SignIn.js
- client/modules/users/components/SignIn.spec.js
Tests for the SignIn react component
> tests for SignIn.js component

- client/modules/customer/components/CustomerEdit.js
> Hide Status Buttons for Pending Customers

- client/modules/users/components/ResetPassword.js
reset password xhr err message fix
> reset password xhr err message fix

- client/modules/users/components/ForgotPassword.js
forgot password xhr err response fix
> forgot password xhr err response fix

- server/lib/mail/mail-helpers.js
send rejected mail only if status is rejected Issue: #272
> send rejected mail only if status is rejected

- client/modules/food/components/packing/PackingList.js
- client/modules/users/components/SignIn.js
> fix Login redirect

- README.md
- client/modules/driver/components/driver-assignment/CustomerSelector.js
I made some minor adjustments to make the assign customers screen a bit more clear, but I'm open to suggestions on improving it further. 
Changes:
* Uses Bootstrap's 'danger-alert' to highlight 'no matching customers'
* Adds a 'Customers' header to the list of assigned customers
* Changes 'Customers:' by the dropdown to 'Customers Assigned To:'
> Fix/assign customers ui - fixes #294

- client/modules/food/components/inventory/Category.spec.js
- client/modules/food/components/inventory/FoodCategories.js
- client/modules/food/components/inventory/FoodCategories.spec.js
- client/modules/food/components/inventory/FoodItems.js
- client/modules/food/components/inventory/FoodItems.spec.js
- client/modules/food/components/inventory/NewCategory.spec.js
> Tests for food inventory React components

- server/controllers/donation.js
- server/routes/donation.js
- server/tests/integration/donation.spec.js
Per Issue #130 I've started some an integration test for donations. If this looks good, I'll continue with the rest of the donation tests.
> creates donations - integration test

- client/modules/food/components/packing/PackingList.js
Fix PackingList with unselectabler.
> fix packingList

- server/controllers/users/profile.js
- server/tests/integration/user.spec.js
the call to lean() is removing the user.save function which is required later in the function.  Also added some tests since this was not being caught by them.
> Fix server error when updating a user

- client/modules/food/components/packing/Packages.js
> Added column Customer name to Packages grid

- client/Application.js
- client/app.js
- client/application.css
- client/store/index.js
- client/store/middleware/notify.js
- package.json
Notify on submitting form field with errors and on settings saved succesfully.
It uses a redux middleware that can be very flexible, all notifications logic is in one file.
This PR resolves #154
> Add s-alert notifications

- server/controllers/food.js
> Fix error 'unathorized' while an user tries to get the food list

- client/modules/users/components/SignUp.js
- server/models/package.js
- server/tests/integration/user.spec.js
> Add the displaying of password errors on the signup page

- client/modules/users/UserRouter.js
> fix: sign-in authentication issue

- client/application.css
Removed grey background from disabled checkbox and added not-allowed cursor.
Closes #300
> Fixed disabled checkbox in packing page

- client/app.js
- client/modules/core/components/sidebar/SidebarMenu.js
- package-lock.json
- package.json
Updated AdminLTE to 2.4.3 to fix sidebar menu issues.
closes #133
> Updated AdminLTE and made fixes according to update guide

- server/controllers/customer.js
Changed status update notifications according to discussion on issue #320 
close #320
> Fixed issues with notifications of user status changes
